saml_metadata:
    path:     /saml/metadata/{idp}
    defaults: { _controller: Hslavich\OneloginSamlBundle\Controller\SamlController::metadataAction }

saml_acs:
    path:     /saml/acs
    defaults: { _controller: Hslavich\OneloginSamlBundle\Controller\SamlController::assertionConsumerServiceAction }

saml_login:
    path:     /saml/login/{idp}
    defaults: { _controller: Hslavich\OneloginSamlBundle\Controller\SamlController::loginAction }

saml_logout:
    path:     /saml/logout
    defaults: { _controller: Hslavich\OneloginSamlBundle\Controller\SamlController::singleLogoutServiceAction }

saml_metadata_default:
    path: /saml/metadata
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /saml/metadata/default
        permanent: false

saml_login_default:
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /saml/login/default
        permanent: false
